version: '3.7'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - motion_assignment:/var/lib/mysql

  api:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    command: npm run start:prod
    depends_on:
      - mysql

volumes:
  motion_assignment:
